"""phase_9_model

Revision ID: 7d3eb6f3c07f
Revises: 958501073438
Create Date: 2026-07-27 19:01:56.629074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d3eb6f3c07f'
down_revision: Union[str, Sequence[str], None] = '958501073438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complaint_source', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('product_strength', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('manufacturing_date', sa.Date(), nullable=True))
    op.add_column('complaints', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('complaints', sa.Column('quantity_affected', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('complaint_type', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('complaint_date', sa.Date(), nullable=True))
    op.add_column('complaints', sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'metadata_info')
    op.drop_column('complaints', 'complaint_date')
    op.drop_column('complaints', 'complaint_type')
    op.drop_column('complaints', 'quantity_affected')
    op.drop_column('complaints', 'expiry_date')
    op.drop_column('complaints', 'manufacturing_date')
    op.drop_column('complaints', 'product_strength')
    op.drop_column('complaints', 'complaint_source')
    # ### end Alembic commands ###
