"""Add product_name to complaints

Revision ID: 873e704f5cf6
Revises: 7d3eb6f3c07f
Create Date: 2026-07-28 11:20:00.301052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873e704f5cf6'
down_revision: Union[str, Sequence[str], None] = '7d3eb6f3c07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('product_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'product_name')
    # ### end Alembic commands ###
